### ISSUE TITLE
Definiendo el REST

### ISSUE THREAD

**Issue by hcarreras** [Samu92/AGA-OSL#14]
Vale chicos, abro este hilo para organizarnos un poco. Quiero terminar el rest cuando antes.
El nombre de nuestro recurso es Stock.
El index ahora mismo devuelve un json (o html) con todos los datos Ejemplo:
[
{
Referencia: "1",
revisado: "",
Localización: "Oficina, en uso",
Tipo: "Sobremesa",
CPU: "Intel(R) Pentium(R) Dual CPU E2180",
MHz: "2048",
RAM: "1024",
Disco Duro (GB): "160",
CD/DVD: "Grabadora DVD",
Floppy: "No",
Ethernet: "Sí",
Fuente Alimentación: "420 W",
Notas: "",
Campaña número: "OSL",
Puntuación CPU: "71433554238",
Puntuación RAM: "10",
Puntuación DD: "10",
Puntuación: "85716777119"
},
{
Referencia: "2",
revisado: "x",
Localización: "Almacén",
Tipo: "Sobremesa",
CPU: "Intel(R) Pentium(R) Dual CPU E2180",
MHz: "2048",
RAM: "3072",
Disco Duro (GB): "160",
CD/DVD: "Grabadora DVD",
Floppy: "No",
Ethernet: "Si",
Fuente Alimentación: "550 W",
Notas: "OSL-TAC-2 -> Serafin",
Campaña número: "OSL",
Puntuación CPU: "7,14",
Puntuación RAM: "10",
Puntuación DD: "10",
Puntuación: "8,57"
},
...
]

Al show se le pasa un :id, este ahora mismo es **el numero de fila**. Este devuelve la fila completa por ejemplo una peticion a stock/1.json devolvería:
{
Referencia: "1",
revisado: "",
Localización: "Oficina, en uso",
Tipo: "Sobremesa",
CPU: "Intel(R) Pentium(R) Dual CPU E2180",
MHz: "2048",
RAM: "1024",
Disco Duro (GB): "160",
CD/DVD: "Grabadora DVD",
Floppy: "No",
Ethernet: "Sí",
Fuente Alimentación: "420 W",
Notas: "",
Campaña número: "OSL",
Puntuación CPU: "71433554238",
Puntuación RAM: "10",
Puntuación DD: "10",
Puntuación: "85716777119"
}

Ahora hay que crear los metodos crear editar y eliminar. De que modo los vamos a gestionar?
Para empezar hay que ver como se manejan los datos. Se va a modificar desde la web? desde el movil? desde los dos?
¿Esta bien que manejemos las filas enteras en lugar de solo datos de fila/columna?

**Comment by Samu92** [comment]
Buenos días Hari,

### ¿Se va a modificar desde la web? ¿desde el móvil? ¿desde los dos?

desde mi punto de vista habría que permitir crear, editar y eliminar en ambos clientes mediante los formularios correspondientes. Teniendo en cuenta la lectura de los códigos Qr, su generación y lectura .
NOTA: Habría que ver como almacenar y dónde almacenar esos códigos Qr generados.

###¿De qué modo los vamos a gestionar?

####Crear:
- El número de referencia será automático, se incrementará automáticamente.
- Se insertarán todos los campos mediante un formulario, ya sea en la web o en el móvil, los datos de este formulario serán enviados al REST mediante argumentos de una función ubicada en el REST o un json (Aún no sé como funcionan las llamadas desde cliente).
- En la creación, en ambas partes, tanto en la web como en el móvil, se generará un código Qr que irá almacenado en algún lugar y tendrá como identificador el número de referencia de la fila.
- El REST provocará una respuesta insertando la nueva fila en el documento de google docs.

####Editar
- En ambos clientes, tanto en la web como en el móvil, se debería de dar la posibilidad de mostrar todas las filas, poder seleccionar la que se quiera y mediante un formulario recuperar los datos de la fila seleccionada. 
- Esto se haría mediante una llamada al REST para recuperar los datos de una fila específica. 
- Una vez recuperados los datos, estos se podrían cambiar al gusto y una vez modificado realizar una llamada a una función del REST que updatee la fila con los nuevos datos.

####Eliminar
- Similar al editar, pero eliminando la fila seleccionada.

###¿Está bien que manejemos las filas enteras en lugar de solo los datos de fila/columna?

- Bueno, esto es un poco relativo, tal como he descrito en las diferentes partes, habrá un formulario que mostrará TODOS los datos de la fila seleccionada, el usuario podrá modificar, crear o lo que sea al gusto y habrá un botón o algo para CONFIRMAR, ENVIAR ... todos los datos al REST. Por lo tanto el REST trabajará con la fila entera.

Esto es lo más básico que tendríamos que tener hecho para que el proyecto vaya tomando forma. Por favor, leed todos esto y poned las dudas o modificaciones que veáis convenientes. Es muy importante que todos sigamos las mismas instrucciones para no liarnos.

Es importante que dejemos aclarado como vamos a hacer la generación de los Qr y dónde vamos a almacenarlos por si habría que introducir algún cambio en REST para que almacenase los Qr en el docs ó fuesen los clientes los que realizaran el almacenamiento en alguna página de almacenamiento de imágenes ó servidor.

**Comment by hcarreras** [comment]
Problemas:
Realmente con la hoja de cálculo donde tenemos todo almacenado, es mucho más fácil coger una fila por su número de fila que por su referencia. Podríamos decir que no está indexado.
Ahora mismo estamos funcionando como id de la fila su número. Es decir cuando haces stock/4.json estás pidiendo la 4º fila (sin contar encabezados). 
Sin embargo, por razones obvias queremos que el id sea la referencia. 
Posible solución: Recorrer fila por fila hasta encontrar la referencia que estamos buscando. El problema con esto es que esto es totalmente lento e ineficaz. Pero que podemos hacer teniendo en cuenta la estructura de datos que tenemos?
Problema: Asignar la referencia. Lo lógico como tu bien dices Samu, es que sea un valor que incremente en uno. Sin embargo, dónde se lleva la cuenta?
Posible solución: Ponerlo en algún lado en la hoja de cálculos. Cada vez que queramos asignar una nueva referencia, vemos cual es la última que se ha asignado, la incrementamos en uno y damos ese número a la nueva linea. El problema de esto es que es altamente inestable. Si alguien por lo que sea cambia ese número en la hoja de cálculo jode todo el tinglao. De nuevo pregunto, alguna solución mejor sin usar db?

En cuanto a los QR, la verdad es que no tengo ninguna experiencia con ellos. Que es lo que se debe guardar? una imagen? un código?

Por otro lado estoy investigando para no pedir autentificación a la hora de ver el stock. Sin embargo para modificar el excel será obligatorio.

**Comment by hcarreras** [comment]
Por otra parte, no tengo ni idea de cómo se hace la autentificación de google drive en el móvil, pero va a ser necesaria. Alguien lo puede ir mirando?

**Comment by ppruiz** [comment]
@hcarreras en el caso de los codigos QR supongo que lo que queremos es guardar imagenes, que seran las que a traves del reconocimiento de éstas proporcionen los datos asociados a ellas, no?

**Comment by hcarreras** [comment]
@ppruiz pues supongo... hay que mirar también como se generan (me imagino que estará todo hecho) y si los imagenes tienen algun formato especial o son png.

Otros comentarios sobre el REST que no se han tenido en cuenta hasta ahora:
A la hora de **eliminar** una fila, quedará una fila en blanco. la dejamos en blanco? o movemos todas las lineas una para arriba. Si el documento solo lo va a usar la aplicación, lo mejor es que lo dejemos en blanco. Si no, quizás convenga moverlos. En el caso de moverlos hay que usar como :id la referencia si o si.

A la hora de añadir: se añade en la primera fila vacia? o en la ultima? depende de la eliminación claro.

**Comment by Samu92** [comment]
@hcarreras 

Problema: Asignar la referencia. Lo lógico como tu bien dices Samu, es que sea un valor que incremente en uno. Sin embargo, dónde se lleva la cuenta?

Tienes razón, es un problema, recorrer todas las filas sería ineficiente, esto depende del número de filas claro está... y ver la última asignada también sería inseguro.

Como no tenemos base de datos tampoco podemos guardar el número de referencia ahí.

La más segura pero ineficiente sería comprobar la referencia de la última fila. Habría que empezar haciéndolo así hasta que se nos ocurra algo mejor. Y esperemos que nadie cambie la referencia de la última fila a mano, si no, sería un caos... Si tenéis ideas mejores proponerlas.

En cuanto a los códigos Qr habría que mirar a ver si podemos guardar la imagen en el docs añadiendo un campo más, que se llame por ejemplo ruta_qr o directamente contenta la imagen.
Como dice Harí, estará todo hecho, se generaría un Qr con la referencia "incrustada". Al leer dicho Qr, se leería dicha referencia y con ella se llamaría al REST y se recuperarían los datos de esa referencia. La idea es sencilla.

A la hora de eliminar una fila:
- Como tu dices, si el documento solo se va a utilizar a través de la aplicación da igual que haya espacios en blanco. Eso te lo dejo a tu elección. En mi opinión lo mejor sería recuperar filas por id de referencia, pero no sé hasta cuanto de complicado es eso. Mirar por número de fila me parece un poco inseguro.

A la hora de añadir:
- Bueno, el orden de las referencias va de 1....n de arriba a abajo, lo mejor sería añadir en la última fila en blanco como se ha hecho hasta ahora manualmente.

**Comment by Samu92** [comment]
@ppruiz lo de la autentificación de google drive en el móvil supongo que será teniendo la app de google docs instalada con la cuenta y tal... parecido al ordenador. Pablo, échale un vistazo, prueba a recuperar el stock del REST a ver si todo funciona bien y hace falta identificación.

@hcarreras ¿es realmente necesario autentificar los clientes? ¿No basta solamente con que se autentifique el REST que es el que va a mover datos?

**Comment by JAntonioMarin** [comment]
@Samu92 Lo del login con la aplicación de android lo hago yo este fin de semana pruebo al pedir la aplicación los datos del REST a ver que pasa.

@ppruiz Tienes que conseguir para la aplicación generar los QR no solo leerlos

**Comment by hcarreras** [comment]
@Samu92 
En cuanto a la referencia. No podemos mirar cual es la última referencia, ha de ser guardada en otro sitio. Imagina el caso en el que se crear un nuevo stock y se le asigna la referencia 52. Luego se borra este stock. Al añadir uno nuevo, se le volvería a asignar la referencia 52. Esto es incorrecto, los id deben de ser únicos siempre. Por lo que creo que crearé en la hoja de cálculo un campo última referencia asignada. 

En cuanto a la autenticación con android:
Imaginemos que la aplicación móvil intenta añadir un stock. Hace una petición post para añadir la nueva fila. El problema está en que el servidor necesita verificar que esa persona tiene cuenta (y probablemente acceso) al google drive. El servidor puede ver/editar datos, pero para comunicarse con google necesita dar unas credenciales (que tienen que salir del usuario, no pueden ser estáticas).
Voy a intentar no pedir autenticación para peticiones get (index y show) pero para editar mucho me temo que será necesarias. El cómo hacerlo, ni idea. Pero creo que será algo así como que antes de enviar el formulario, se autentica y una vez tiene las credenciales, hace la petición.

**Comment by hcarreras** [comment]
Este fin de semana cambiaré el id por número de referencia (para solicitar el show). Aviso de antemano que es ineficiente, pero tenemos un compromiso entre eficiencia y "sensación de control". En cualquier caso todo será altamente inestable, pero es lo que tiene trabajar con una hoja de excel que puede ser modificada por otra parte que no es la aplicación. 
Después completaré el REST (editar y eliminar).
Por último (no será este fin de semana seguro), intentaré que no pida la autenticación para el index y el show.
He ordenado estas 3 tareas que voy a hacer por orden de preferencia para que podais trabajar más con la aplicación móvil. Si creeis que debería cambiar las prioridades decidmelo.

**Comment by Samu92** [comment]
Me parece perfecto Harí, como última noticia, Juan, Pablo y yo nos hemos cambiado los clientes, a partir de ahora yo seré el encargado de hacer la aplicación móvil. Le echaré un vistazo a lo de los credenciales.
