### ISSUE TITLE
Urgente - Correciones

### ISSUE THREAD

**Issue by Samu92** [Samu92/AGA-OSL#15]
Para empezar, tener dos repositorios para el código sólo dificulta las cosas para los que corregimos. Es imposible saber qué habéis hecho, ni quién, ni nada. 
La licencia tenéis que tenerla en todo el código. La documentación en un sólo fichero, que vayáis evolucionando. ¿Cómo queréis que vayamos navegando por todos los ficheros para evaluarlo)
No acabo de tener claro si estais usando google drive o Heroku o qué. ¿Por qué no lo alojáis en Google Appspot en vez de en Heroku? ¿Por qué necesita la aplicación tener permiso para acceso a mis aplicaciones? Nadie os var a dar permiso para acceder a nada y menos con unos permisos tan permisivos. 
En resumen: está claro que habéis hecho algo, pero la impresión general es caótica. Dos repositorios, documentación repartida, parece que estéis haciendo dos proyectos diferentes. 
Evitad también subir aplicaciones de ejemplo a cascoporro y más para hacer commit a una persona. Tiene que quedar clara la contribución de cada uno.

En general, bastante caótico, como os he indicado en el commit. Tenéis que decidiros por una aplicación, una documentación, un proyecto sólo y trabajar todos en él.

Chicos, hay que ponerse a corregir todo lo que nos indica. Intentaré corregir todo lo que pueda hoy.

**Comment by JAntonioMarin** [comment]
Si esta claro voy a hablar ahora mismo con el para que me aclare si quiere ciertas cosas.

**Comment by JAntonioMarin** [comment]
Bueno he hablado con el, la cuestión es que no tenemos nada, la idea es que tenemos que poner todo en GoogleAppEngine (DOCS, REST y Web), La aplicación Android por supuesto iría a parte y no le importaría tanto. La cuestión es que tenemos que entregar en dos semanas... asi que tenemos que ponernos ya.

Las diferentes partes hay que que ponerlas dentro de este repositorio en submodulos (git-modules).
Nos falta la integración continua.
Para Pablo y para mi podemos subir nota, la tenemos así porque no hemos colaborado en hacer los test de la aplicación, vamos a realizar mas test para las distintas aplicaciones.
Las documentaciones me ha dicho que podemos poner una documentación en el readme que conecte con todas las documentaciones.
TODO EN UN MISMO REPOSITORIO.

Ahora hablamos en SPSI

**Comment by ppruiz** [comment]
Esta bien, hablamos en persona y aclaramos el trabajo.

**Comment by Samu92** [comment]
Vale, hay que ponerse a ello. Corregiré primero que nada la documentación. Hay que colocar todo en GoogleAppEngine y en el mismo repositorio (Poneos de acuerdo con Harí para subir tanto lo que llevéis hecho de la web como el REST) , voy a investigar lo de los git-modules y a ver si puedo averiguar como se hace. Pondré toda la documentación en el readme del repositorio.

**Comment by Samu92** [comment]
Vale, ya he averiguado como se hacen los submodulos, si veis ya he creado el submodulo de Android.

¿Cómo crear un submodulo?
Lo primero que tenéis que hacer es crearos un repositorio propio. Una vez creado nos vamos al repositorio clonado de AGA-OSL y ejecutamos la siguiente orden:

git submodule add <AQUÍ LA DIRECCIÓN HTTP DEL REPOSITORIO CREADO>

No hace falta hacer git add

Inmediatamente hacemos git commit y git push origin master para subir el módulo al repositorio AGA-OSL

Los submodulos son referencias (carpetas) a otros repositorios externos. Podemos tratarlos como si fuesen repositorios dentro de un repositorio principal.

**Comment by Samu92** [comment]
@hcarreras Harí, aquí tienes un enlace para subir el REST en appspot

http://rails-primer.appspot.com/

**Comment by hcarreras** [comment]
Vale, ya he añadido el subrepo.
Voy a trabajar en este orden.
Hoy voy a hacer el update y destroy del rest, para que podáis hacer la aplicación móvil y el formulario.
Mañana intentaré trabajar para subirlo a google app
Miércoles intentaré que no pida credenciales para el index y el show

**Comment by Samu92** [comment]
Vale Harí ;), ve informándonos

**Comment by hcarreras** [comment]
He cambiado el orden de mi trabajo por miedo a que tuviese luego que cambiar más código!
Ya funciona el REST (index y show) sin pedir credenciales. 
¿Cómo funciona ahora?
He creado una cuenta de Google llamada agaoslrails@gmail.com. La aplicación se loguea con esta cuenta y es la aplicación la que hace todas las llamadas. Luego la devuelve por json.
¿Porqué no lo has hecho así antes?
Pues porque la documentación de la librería que estaba usando deja bastante que desear y todo lo que encontraba por internet lo hacía con otro usuario. 
Podeis comprobar que el [repo](http://aga-osl.herokuapp.com/) ya funciona sin pedir credenciales.
Ahora será mucho más fácil la app móvil y los tests.

**Comment by Samu92** [comment]
Perfecto Harí!!, ahora todo será más sencillo :dancer:

**Comment by ppruiz** [comment]
Buen trabajo Hari :D

**Comment by hcarreras** [comment]
Vale, escribo para informaros de mis avances. Prometí un poco más de lo que he hecho, pero bueno, hago un poco todos los dias (mis dias estan siendo un poco locura).
Ahora el show tiene como id la referencia en lugar del numero de fila. Esto era necesario para hacerlo un poco más estable, además de que es lo lógico.
Por otra parte he mejorado bastante el código y he eliminado código de la implementación antigua (que pedía autenticarse al usuario).
Mañana más y mejor! :)

**Comment by JAntonioMarin** [comment]
Repositorio para la web creado,  submodulo linkado al principal y web desplegada en Google Apple Engine,  es fácil desplegará así que si queréis al final podemos juntarlas todas dentro de la misma app

**Comment by Samu92** [comment]
Si, lo mejor va a ser colocar todo en appspot.

**Comment by Samu92** [comment]
Mañana con tranquilidad haré un resumen de las cosas que faltan.

**Comment by ppruiz** [comment]
Ok, en breves subiré la parte de documentación de Integración Continua.

**Comment by JAntonioMarin** [comment]
Yo ya he estado mirando los test unitarios para el php, pero los subiré cuando tenga mas test que hacer a las diferentes funciones de la pagina, estaría bien que estuviera listo el insertar y el borrar (Aunque este ultimo no debería estar, ya que estaría bien tener un registro de los que se tuvo, como en las empresas se obliga a guardar los datos durante 5 años).

@hcarreras estuve viendo que si haces la llamada stock/3.json y el 3 no existe en el indice devuelve la primera fila siempre, creo que debería estar vacío, no se si te has dado cuenta.

**Comment by hcarreras** [comment]
Estoy trabajando en editar, borrar  y crear. El problema es que no se edita el documento por alguna razón. Estoy en ello.
Si, tengo que arreglar la respuesta del servidor cuando la referencia no existe.

**Comment by Samu92** [comment]
@JAntonioMarin  @ppruiz @hcarreras 
Dejo aquí un enlace a un documento de google que estoy haciendo en estos momentos.

https://docs.google.com/document/d/1aY6bwWLNVAhc91OPJflwDRFZ9RhVMzVc0_Z6UXUpZZ8/edit?usp=sharing

Id echándole un vistazo, por favor. :D

**Comment by hcarreras** [comment]
Create, Update y Destroy funcionando. (no lo he deployado ya que vamos a cambiar de servers)

**Comment by ppruiz** [comment]
Perfecto @hcarreras! @JAntonioMarin y yo nos ponemos el miercoles con la parte de la web.

**Comment by hcarreras** [comment]
Perdonad por no haber puesto antes, se me pasó, pero no es tan obvio.
Ejemplo de como usar el REST con curl:
Get del recurso (index) en formato json

    curl -X GET -H "Content-Type: application/json"  http://aga-osl.herokuapp.com/stock

Get de una instancia del recurso (show) en formato json

    curl -X GET -H "Content-Type: application/json"  http://aga-osl.herokuapp.com/stock/:referencia
    curl -X GET -H "Content-Type: application/json"  http://aga-osl.herokuapp.com/stock/226

Para crear una instancia (create) usamos POST. Le tenemos que pasar los datos que va a ser creados en un array llamado data. La referencia se asignará automaticamente, por lo que tenemos que pasar en orden el resto de datos. Si queremos alguno vacio, siempre se le puede pasar un string vacio ''.

    curl -X POST -H "Content-Type: application/json" -d "{\"data\":[\"Testing con curl\",\"no importante\",\"\",\"borrable\"]}"  http://aga-osl.herokuapp.com/stock

Para editar una instancia (update) usamos PUT. Le tenemos que pasar los nuevos datos como si fuese un create.

    curl -X PUT -H "Content-Type: application/json" -d "{\"data\":[]}"  http://aga-osl.herokuapp.com/stock/:referencia
    curl -X PUT -H "Content-Type: application/json" -d "{\"data\":[\"Nuevos datos\",\"no son importante\",\"\",\"\",\"borrable\"]}"  http://aga-osl.herokuapp.com/stock/389

Por último para borrar usamos el método DELETE

    curl -X "DELETE" localhost:3000/stock/:referencia
    curl -X "DELETE" localhost:3000/stock/390


Espero que sirva de ayuda. Esto lo meteré en la documentación final.

**Comment by hcarreras** [comment]
Ya está listo el index limitado.
Al index se le puede pasar un parámetro opcional llamado "request_data". Este contendrá un array de hashes, con las claves referencia y ultima_modificacion.
Ejemplo:
{request_data: [{referencia: 1, ultima_modificacion: "14/01/2015"}, {referencia: 226, ultima_modificacion: "11/01/2015"}] '

El servidor devolverá un json con un array de todos los equipos que cumplan esas condiciones.
Si ningún parámetro es pasado al servidor, entonces devolverá todos.
