### ISSUE TITLE
Integración continua

### ISSUE THREAD

**Issue by Samu92** [Samu92/AGA-OSL#17]
http://4trabes.com/2007/07/26/instalando-cruisecontrol-rb-una-herramienta-de-integracion-continua-para-aplicaciones-ruby-on-rails/

Este enlace es mucho más completo.

Vamos a ver si dejamos esto listo. @ppruiz

**Comment by ppruiz** [comment]
De acuerdo continuo con ello. Hablamos por gmail,

**Comment by Samu92** [comment]
Cambiamos la herramienta de integración continua, utilizamos Jenkins.

http://178.62.92.114:8080/
